const $=x=>document.getElementById(x);
$("menu").onclick=()=>$("nav").classList.toggle("open");
const data={6:["Mathematics","Science","English","Social Science"],7:["Mathematics","Science","English","Social Science"],8:["Mathematics","Science","English","Social Science"],9:["Mathematics","Science","English","Social Science"],10:["Mathematics","Science","English","Social Science"],11:["Mathematics","Physics","Chemistry","English"],12:["Mathematics","Physics","Chemistry","Biology","English"]};
Object.keys(data).forEach(c=>{let b=document.createElement("button");b.className="classBtn";b.textContent="Class "+c;b.onclick=()=>openClass(c);$("classesGrid").appendChild(b)});
function openClass(c){$("classPanel").innerHTML="<div class='card'><h3>Class "+c+"</h3><p>Select a subject:</p>"+data[c].map(s=>"<button class='subject' onclick='showSubject("+JSON.stringify(s)+","+c+")'>"+s+"</button>").join("")+"<p id='subjectMsg'>Choose a subject to continue.</p></div>";$("classPanel").scrollIntoView({behavior:"smooth"})}
function showSubject(s,c){$("subjectMsg").textContent=s+" for Class "+c+" — chapter resources will be added here."}
$("sub").onsubmit=async e=>{e.preventDefault();$("subMsg").textContent="Submitting...";try{let r=await fetch("/api/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("subEmail").value})});let d=await r.json();$("subMsg").textContent=d.message||"Submitted";if(r.ok)e.target.reset()}catch{$("subMsg").textContent="Unable to connect."}};
$("enrollForm").onsubmit=async e=>{e.preventDefault();$("enrollMsg").textContent="Submitting enrollment...";try{let r=await fetch("/api/enroll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("name").value,className:$("className").value,email:$("email").value})});let d=await r.json();$("enrollMsg").textContent=d.message||"Submitted";if(r.ok)e.target.reset()}catch{$("enrollMsg").textContent="Unable to connect."}};
const searchable=["Learning Hub","Classes 6–12","AI & Digital Skills","Practice Zone","Resource Library","Student Progress","Faculty / Mentors","Research Program","Idea-to-Project","Communication Lab","Career Explorer","Challenge Arena","Announcements","Stay Updated","Enroll"];
$("searchBtn").onclick=()=>{let q=$("q").value.toLowerCase();let h=searchable.filter(x=>x.toLowerCase().includes(q));$("results").innerHTML=h.length?h.map(x=>"<p>"+x+"</p>").join(""):"<p>No matching section found.</p>"};